/**
 * Drafted content table.
 *
 * Displays the field values generated by the AI agent in a
 * table format. Supports flat fields and nested inline entities
 * (e.g. contacts). Each row has a reject/accept toggle, and
 * inline entities render as expandable cards with sub-fields.
 */

import DOMPurify from "dompurify";
import {
  Check,
  ChevronDown,
  ChevronRight,
  Loader2,
  RotateCcw,
  Save,
  X,
} from "lucide-react";
import { useMemo, useState } from "react";
import type { DraftedField, DraftedInlineEntity } from "../store";
import { toggleFieldRejected, useDraftingSlice } from "../store";

/** Props for the content table. */
interface ContentTableProps {
  onRegenerate: (rejectedFields: string[]) => void;
  onSave: () => void;
}

/** Renders sanitized HTML content for formatted text fields. */
function HtmlFieldValue({ html }: { html: string }) {
  const clean = useMemo(() => DOMPurify.sanitize(html), [html]);
  return (
    <div
      className="prose prose-sm max-w-none text-gray-700"
      dangerouslySetInnerHTML={{ __html: clean }}
    />
  );
}

/** Renders a field value based on its type. */
function FieldValue({
  field,
  isStreaming,
}: {
  field: DraftedField;
  isStreaming: boolean;
}) {
  if (field.inlineEntities && field.inlineEntities.length > 0) {
    return <InlineEntities entities={field.inlineEntities} />;
  }
  if (field.type === "html" && field.value) {
    return (
      <div className="flex items-end">
        <HtmlFieldValue html={field.value} />
        {isStreaming && <StreamingCursor />}
      </div>
    );
  }
  return (
    <p className="text-sm text-gray-700">
      {field.value}
      {isStreaming && <StreamingCursor />}
    </p>
  );
}

/** Renders a list of inline entity cards (e.g. contacts). */
function InlineEntities({ entities }: { entities: DraftedInlineEntity[] }) {
  return (
    <div className="space-y-2">
      {entities.map((entity, idx) => {
        // Use the name sub-field as a stable key when available.
        const key =
          entity.fields.name?.value ?? `${entity.bundle}-${String(idx)}`;
        return <InlineEntityCard key={key} entity={entity} index={idx} />;
      })}
    </div>
  );
}

/** A single expandable inline entity card. */
function InlineEntityCard({
  entity,
  index,
}: {
  entity: DraftedInlineEntity;
  index: number;
}) {
  const [expanded, setExpanded] = useState(true);
  const subFields = Object.entries(entity.fields);

  // Use the first field's value as the card title (usually "name").
  const titleField = entity.fields.name ?? subFields[0]?.[1];
  const title = titleField?.value ?? `${entity.bundleLabel} #${index + 1}`;

  return (
    <div className="rounded-md border border-gray-200 bg-white">
      {/* Card header */}
      <button
        type="button"
        onClick={() => setExpanded(!expanded)}
        className="flex w-full cursor-pointer items-center gap-2 px-3 py-2 text-left hover:bg-gray-50"
      >
        {expanded ? (
          <ChevronDown size={14} className="shrink-0 text-gray-400" />
        ) : (
          <ChevronRight size={14} className="shrink-0 text-gray-400" />
        )}
        <span className="text-sm font-medium text-gray-800">{title}</span>
        <span className="text-xs text-gray-400">{entity.bundleLabel}</span>
      </button>

      {/* Sub-fields (collapsible) */}
      {expanded && (
        <div className="border-t border-gray-100 px-3 py-2">
          <dl className="space-y-1.5">
            {subFields.map(([name, subField]) => (
              <div key={name} className="flex gap-3 text-sm">
                <dt className="w-24 shrink-0 text-gray-400">
                  {subField.label}
                </dt>
                <dd className="min-w-0 text-gray-700">{subField.value}</dd>
              </div>
            ))}
          </dl>
        </div>
      )}
    </div>
  );
}

/** Confirmation dialog for saving the draft. */
function SaveConfirmDialog({
  onConfirm,
  onCancel,
}: {
  onConfirm: () => void;
  onCancel: () => void;
}) {
  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40">
      <div className="mx-4 w-full max-w-sm rounded-lg bg-white p-6 shadow-xl">
        <h3 className="text-base font-semibold text-gray-900">
          Save draft revision?
        </h3>
        <p className="mt-2 text-sm text-gray-500">
          This will save the drafted content as a new{" "}
          <strong>unpublished</strong> revision. The current published version
          will not be affected. You can review and publish the revision later.
        </p>
        <div className="mt-5 flex justify-end gap-3">
          <button
            type="button"
            onClick={onCancel}
            className="cursor-pointer rounded-md border border-gray-300 px-4 py-2 text-sm font-medium text-gray-700 hover:bg-gray-50"
          >
            Cancel
          </button>
          <button
            type="button"
            onClick={onConfirm}
            className="flex cursor-pointer items-center gap-1.5 rounded-md bg-blue-600 px-4 py-2 text-sm font-medium text-white hover:bg-blue-700"
          >
            <Save size={14} />
            Save as draft
          </button>
        </div>
      </div>
    </div>
  );
}

/** Blinking cursor shown at the end of a field being streamed. */
function StreamingCursor() {
  return (
    <span
      className="ml-0.5 inline-block h-4 w-0.5 bg-blue-500"
      style={{ animation: "blink 0.8s step-end infinite" }}
    />
  );
}

/** The content drafting table with reject/accept controls. */
export function ContentTable({ onRegenerate, onSave }: ContentTableProps) {
  const { draftedFields, rejectedFields, streamingFieldName, updatedFields } =
    useDraftingSlice();
  const fieldEntries = Object.entries(draftedFields);
  const [showConfirm, setShowConfirm] = useState(false);

  if (fieldEntries.length === 0) {
    return null;
  }

  const rejectedCount = rejectedFields.size;

  return (
    <div className="flex min-h-0 flex-1 flex-col">
      {/* Header */}
      <div className="flex items-center justify-between border-b border-gray-200 px-4 py-3">
        <h2 className="text-sm font-semibold text-gray-900">Drafted Content</h2>
        <div className="flex items-center gap-2">
          {rejectedCount > 0 && (
            <button
              type="button"
              onClick={() => onRegenerate([...rejectedFields])}
              className="flex cursor-pointer items-center gap-1.5 rounded-md border border-gray-300 px-3 py-1.5 text-xs font-medium text-gray-700 hover:bg-gray-50"
            >
              <RotateCcw size={12} />
              Regenerate {rejectedCount} field
              {rejectedCount > 1 ? "s" : ""}
            </button>
          )}
          <button
            type="button"
            onClick={() => setShowConfirm(true)}
            className="flex cursor-pointer items-center gap-1.5 rounded-md bg-blue-600 px-3 py-1.5 text-xs font-medium text-white hover:bg-blue-700"
          >
            <Save size={12} />
            Save draft
          </button>
        </div>
      </div>

      {/* Field rows */}
      <div className="min-h-0 flex-1 overflow-y-auto">
        {fieldEntries.map(([name, field]) => {
          const isRejected = rejectedFields.has(name);
          const isUpdated = updatedFields.has(name);
          const isFieldStreaming = streamingFieldName === name;
          return (
            <div
              key={name}
              className={`border-b border-gray-100 px-4 py-3 transition-colors duration-700 ${
                isRejected
                  ? "bg-red-50"
                  : isUpdated
                    ? "bg-blue-50"
                    : "hover:bg-gray-50/50"
              }`}
            >
              {/* Field header: streaming spinner or toggle + label */}
              <div className="mb-1.5 flex items-center gap-3">
                {isFieldStreaming ? (
                  <div className="flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-blue-100 text-blue-500">
                    <Loader2 size={12} className="animate-spin" />
                  </div>
                ) : (
                  <button
                    type="button"
                    onClick={() => toggleFieldRejected(name)}
                    className={`flex h-5 w-5 shrink-0 cursor-pointer items-center justify-center rounded-full transition-colors ${
                      isRejected
                        ? "bg-red-100 text-red-600 hover:bg-red-200"
                        : "bg-green-100 text-green-600 hover:bg-green-200"
                    }`}
                    title={
                      isRejected ? "Mark as accepted" : "Reject this field"
                    }
                  >
                    {isRejected ? <X size={12} /> : <Check size={12} />}
                  </button>
                )}
                <div>
                  <span
                    className={`text-sm font-medium ${
                      isRejected ? "text-red-700 line-through" : "text-gray-900"
                    }`}
                  >
                    {field.label}
                  </span>
                  <span className="ml-1.5 text-xs text-gray-400">{name}</span>
                </div>
              </div>

              {/* Field value */}
              <div className={`pl-8 ${isRejected ? "opacity-50" : ""}`}>
                <FieldValue
                  field={field}
                  isStreaming={streamingFieldName === name}
                />
              </div>
            </div>
          );
        })}
      </div>

      {/* Save confirmation dialog */}
      {showConfirm && (
        <SaveConfirmDialog
          onConfirm={() => {
            setShowConfirm(false);
            onSave();
          }}
          onCancel={() => setShowConfirm(false)}
        />
      )}
    </div>
  );
}
