/**
 * Drafted content table.
 *
 * Simple two-column table displaying the raw field values
 * generated by the AI agent. First column is the field name,
 * second column shows the value (HTML rendered for formatted
 * text, JSON for complex values, plain text for scalars).
 */

import DOMPurify from "dompurify";
import { Save } from "lucide-react";
import { useMemo, useState } from "react";
import { useDraftingSlice } from "../store";

/** Props for the content table. */
interface ContentTableProps {
  onSave: () => void;
}

/**
 * Derives a human-readable label from a field machine name.
 */
function labelFromName(name: string): string {
  return name
    .replace(/^field_/, "")
    .replace(/_/g, " ")
    .replace(/\b\w/g, (c) => c.toUpperCase());
}

/**
 * Extracts a display-friendly value from a Drupal field array.
 *
 * Drupal fields are arrays of items like [{"value": "text"}].
 * Returns {text, isHtml} for rendering.
 */
function extractFieldDisplay(val: unknown): {
  text: string;
  isHtml: boolean;
  isComplex?: boolean;
  items?: unknown[];
} {
  // Single scalar.
  if (typeof val === "string") return { text: val, isHtml: false };
  if (typeof val === "number" || typeof val === "boolean")
    return { text: String(val), isHtml: false };

  // Drupal field array: [{value: "...", format: "full_html"}].
  if (Array.isArray(val) && val.length > 0) {
    const first = val[0];

    // Formatted text with HTML.
    if (
      first &&
      typeof first === "object" &&
      "value" in first &&
      "format" in first
    ) {
      return { text: String(first.value ?? ""), isHtml: true };
    }

    // Simple value items: [{value: "text"}].
    if (first && typeof first === "object" && "value" in first) {
      // Multiple items: join values.
      if (val.length > 1) {
        const values = val
          .map((item) =>
            typeof item === "object" && item && "value" in item
              ? String(item.value)
              : "",
          )
          .filter(Boolean);
        return { text: values.join(", "), isHtml: false };
      }
      return { text: String(first.value ?? ""), isHtml: false };
    }

    // Reference items: [{target_id: 123}].
    if (first && typeof first === "object" && "target_id" in first) {
      const ids = val
        .map((item) =>
          typeof item === "object" && item && "target_id" in item
            ? String(item.target_id)
            : "",
        )
        .filter(Boolean);
      return { text: `[refs: ${ids.join(", ")}]`, isHtml: false };
    }

    // Complex nested objects (paragraphs, contacts): handled
    // separately by renderInlineEntities in the table cell.
    if (first && typeof first === "object") {
      return { text: "", isHtml: false, isComplex: true, items: val };
    }
  }

  // Null or empty.
  if (val === null || val === undefined) return { text: "", isHtml: false };

  // Fallback: JSON.
  return { text: JSON.stringify(val, null, 2), isHtml: false };
}

/** Renders sanitized HTML content. */
function HtmlValue({ html }: { html: string }) {
  const clean = useMemo(() => DOMPurify.sanitize(html), [html]);
  return (
    <div
      className="prose prose-sm max-w-none text-gray-700"
      dangerouslySetInnerHTML={{ __html: clean }}
    />
  );
}

/**
 * System fields on inline entities that should not be displayed.
 */
const SYSTEM_FIELDS = new Set([
  "status",
  "parent_id",
  "parent_type",
  "parent_field_name",
  "behavior_settings",
  "type",
]);

/**
 * Extracts the bundle name from a Drupal entity's type field.
 * The type field is [{"target_id": "text_block"}].
 */
function extractBundle(item: Record<string, unknown>): string {
  const t = item.type;
  if (Array.isArray(t) && t.length > 0 && typeof t[0] === "object" && t[0]) {
    return String((t[0] as Record<string, unknown>).target_id ?? "");
  }
  return "";
}

/**
 * Extracts the display value from a Drupal field array.
 * Returns the value string and whether it contains HTML.
 */
function extractSubFieldValue(val: unknown): { text: string; isHtml: boolean } {
  if (!Array.isArray(val) || val.length === 0)
    return { text: "", isHtml: false };
  const first = val[0] as Record<string, unknown>;
  if (!first || typeof first !== "object") return { text: "", isHtml: false };
  if ("format" in first && "value" in first) {
    return { text: String(first.value ?? ""), isHtml: true };
  }
  if ("value" in first)
    return { text: String(first.value ?? ""), isHtml: false };
  if ("target_id" in first)
    return { text: String(first.target_id ?? ""), isHtml: false };
  return { text: "", isHtml: false };
}

/** Renders a list of inline entity items (paragraphs, contacts). */
function InlineEntityItems({ items }: { items: unknown[] }) {
  return (
    <div className="space-y-3">
      {items.map((item, idx) => {
        if (!item || typeof item !== "object") return null;
        const record = item as Record<string, unknown>;
        const bundle = extractBundle(record);

        // Collect content fields (skip system fields).
        const contentFields: { name: string; text: string; isHtml: boolean }[] =
          [];
        for (const [key, val] of Object.entries(record)) {
          if (SYSTEM_FIELDS.has(key)) continue;
          const { text, isHtml } = extractSubFieldValue(val);
          if (text) contentFields.push({ name: key, text, isHtml });
        }

        if (contentFields.length === 0) return null;

        return (
          <div
            key={`${bundle}-${String(idx)}`}
            className="rounded border border-gray-200 p-3"
          >
            <div className="mb-2 text-xs font-medium text-gray-500 uppercase">
              {labelFromName(bundle || `item ${idx + 1}`)}
            </div>
            <div className="space-y-2">
              {contentFields.map(({ name, text, isHtml }) => (
                <div key={name}>
                  <div className="text-xs text-gray-400 mb-0.5">
                    {labelFromName(name)}
                  </div>
                  {isHtml ? (
                    <HtmlValue html={text} />
                  ) : (
                    <p className="text-sm text-gray-700">{text}</p>
                  )}
                </div>
              ))}
            </div>
          </div>
        );
      })}
    </div>
  );
}

/** Confirmation dialog for saving the draft. */
function SaveConfirmDialog({
  onConfirm,
  onCancel,
}: {
  onConfirm: () => void;
  onCancel: () => void;
}) {
  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40">
      <div className="mx-4 w-full max-w-sm rounded-lg bg-white p-6 shadow-xl">
        <h3 className="text-base font-semibold text-gray-900">
          Save draft revision?
        </h3>
        <p className="mt-2 text-sm text-gray-500">
          This will save the drafted content as a new{" "}
          <strong>unpublished</strong> revision.
        </p>
        <div className="mt-5 flex justify-end gap-3">
          <button
            type="button"
            onClick={onCancel}
            className="cursor-pointer rounded-md border border-gray-300 px-4 py-2 text-sm font-medium text-gray-700 hover:bg-gray-50"
          >
            Cancel
          </button>
          <button
            type="button"
            onClick={onConfirm}
            className="flex cursor-pointer items-center gap-1.5 rounded-md bg-blue-600 px-4 py-2 text-sm font-medium text-white hover:bg-blue-700"
          >
            <Save size={14} />
            Save as draft
          </button>
        </div>
      </div>
    </div>
  );
}

/** The content table showing drafted field values. */
export function ContentTable({ onSave }: ContentTableProps) {
  const { draftedFields } = useDraftingSlice();
  const entries = Object.entries(draftedFields);
  const [showConfirm, setShowConfirm] = useState(false);

  if (entries.length === 0) return null;

  return (
    <div className="flex min-h-0 flex-1 flex-col">
      {/* Header: fixed height matching the toolbar. */}
      <div className="flex h-12 shrink-0 items-center justify-between border-b border-gray-200 px-4">
        <h2 className="text-base font-semibold text-gray-900">
          Drafted Content
        </h2>
        <button
          type="button"
          onClick={() => setShowConfirm(true)}
          className="flex cursor-pointer items-center gap-1.5 rounded-md bg-blue-600 px-3 py-1.5 text-xs font-medium text-white hover:bg-blue-700"
        >
          <Save size={12} />
          Save draft
        </button>
      </div>

      {/* Field rows */}
      <div className="min-h-0 flex-1 overflow-y-auto">
        <table className="w-full">
          <thead>
            <tr className="border-b border-gray-200 bg-gray-50">
              <th className="px-4 py-2 text-left text-xs font-medium text-gray-500 uppercase">
                Field
              </th>
              <th className="px-4 py-2 text-left text-xs font-medium text-gray-500 uppercase">
                Value
              </th>
            </tr>
          </thead>
          <tbody>
            {entries.map(([name, val]) => {
              const display = extractFieldDisplay(val);
              if (display.text === "" && !display.isComplex) return null;
              return (
                <tr
                  key={name}
                  className="border-b border-gray-100 hover:bg-gray-50/50"
                >
                  <td className="px-4 py-3 align-top">
                    <span className="text-sm font-medium text-gray-900">
                      {labelFromName(name)}
                    </span>
                    <span className="ml-1.5 text-xs text-gray-400 block">
                      {name}
                    </span>
                  </td>
                  <td className="px-4 py-3 align-top">
                    {display.isComplex && display.items ? (
                      <InlineEntityItems items={display.items} />
                    ) : display.isHtml ? (
                      <HtmlValue html={display.text} />
                    ) : (
                      <p className="text-sm text-gray-700">{display.text}</p>
                    )}
                  </td>
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>

      {showConfirm && (
        <SaveConfirmDialog
          onConfirm={() => {
            setShowConfirm(false);
            onSave();
          }}
          onCancel={() => setShowConfirm(false)}
        />
      )}
    </div>
  );
}
