<?php

declare(strict_types=1);

namespace Drupal\oe_ai_assistant\Service;

use Drupal\Core\TempStore\PrivateTempStoreFactory;

/**
 * TempStore-based conversation history management.
 *
 * Provides load, save, and delete operations for conversation
 * message arrays, scoped by collection name and thread ID.
 * Automatically trims history to a configurable number of
 * message pairs on both load and save.
 *
 * Each "message pair" consists of one user message followed by one
 * assistant message. Trimming is applied in terms of pairs (not
 * individual messages) so that the context window always contains
 * complete turns. The maximum number of individual messages stored
 * or returned is therefore $maxPairs * 2.
 *
 * Storage is user-scoped via PrivateTempStore, so conversation threads
 * are not shared across Drupal user sessions.
 */
class ConversationHistory {

  /**
   * Default number of message pairs to retain.
   *
   * A pair is one user message plus one assistant message. This value
   * (10 pairs = 20 messages) balances context quality against the size
   * of the conversation history sent to the LLM on each request.
   */
  private const DEFAULT_HISTORY_LENGTH = 10;

  /**
   * Constructs a new ConversationHistory.
   *
   * @param \Drupal\Core\TempStore\PrivateTempStoreFactory $tempStoreFactory
   *   The private temp store factory used to obtain named store instances.
   *   PrivateTempStore scopes data to the current user session, so each
   *   Drupal user has their own isolated conversation history.
   */
  public function __construct(
    private readonly PrivateTempStoreFactory $tempStoreFactory,
  ) {}

  /**
   * Loads conversation history, trimmed to the last N pairs.
   *
   * Retrieves the stored message array for the given thread and slices
   * it from the end so only the most recent turns are returned. This
   * prevents unbounded context growth while preserving the most relevant
   * recent messages for the LLM.
   *
   * @param string $collection
   *   The TempStore collection name (e.g. 'oe_ai_drafting'). Each plugin
   *   should use its own collection to avoid key collisions between plugins
   *   that share the same thread ID format.
   * @param string $threadId
   *   The thread identifier. Typically a UUID generated by the frontend
   *   and included in every request belonging to the same conversation.
   * @param int $maxPairs
   *   Maximum message pairs to return. Each pair is a user + assistant
   *   message, so the actual message count limit is $maxPairs * 2.
   *
   * @return array
   *   Array of message arrays, each with at least 'role' and 'content'
   *   keys. Returns an empty array when no history exists for the thread.
   */
  public function load(
    string $collection,
    string $threadId,
    int $maxPairs = self::DEFAULT_HISTORY_LENGTH,
  ): array {
    $store = $this->tempStoreFactory->get($collection);
    // Return an empty array when the key does not exist yet (new thread).
    $history = $store->get($threadId) ?? [];
    // Slice from the end: negative offset keeps the last N elements.
    return array_slice($history, -($maxPairs * 2));
  }

  /**
   * Saves conversation history, trimming to the last N pairs.
   *
   * Applies the same trim window as load() before persisting so the stored
   * array never exceeds the configured limit, regardless of how many
   * messages the caller passes in.
   *
   * @param string $collection
   *   The TempStore collection name.
   * @param string $threadId
   *   The thread identifier.
   * @param array $history
   *   The full message array to save. May include tool call/result messages
   *   in addition to user and assistant turns.
   * @param int $maxPairs
   *   Maximum message pairs to retain. Older messages beyond this limit
   *   are dropped from the persisted value.
   */
  public function save(
    string $collection,
    string $threadId,
    array $history,
    int $maxPairs = self::DEFAULT_HISTORY_LENGTH,
  ): void {
    $store = $this->tempStoreFactory->get($collection);
    // Trim before storing so the TempStore value stays bounded.
    $trimmed = array_slice($history, -($maxPairs * 2));
    $store->set($threadId, $trimmed);
  }

  /**
   * Deletes a conversation thread from the store.
   *
   * After deletion, a subsequent load() for the same collection and
   * thread ID will return an empty array as if the thread never existed.
   *
   * @param string $collection
   *   The TempStore collection name.
   * @param string $threadId
   *   The thread identifier to remove.
   */
  public function delete(
    string $collection,
    string $threadId,
  ): void {
    $store = $this->tempStoreFactory->get($collection);
    $store->delete($threadId);
  }

}
