<?php

declare(strict_types=1);

namespace Drupal\oe_ai_assistant\Service;

use Drupal\ai\OperationType\Chat\Tools\ToolsInput;

/**
 * Configuration for a single LLM streaming loop run.
 *
 * Captures all inputs needed by LlmStreamingLoop::run(). The class is an
 * immutable value object: every property is set at construction time and
 * exposed as a read-only public property so the loop service can access
 * them without any getter boilerplate.
 *
 * The toolExecutor callback is the primary extension point: each AI
 * assistant plugin provides a closure that handles its own tool calls,
 * keeping tool-specific logic out of the generic loop service.
 */
class LlmLoopConfig {

  /**
   * Constructs a new LlmLoopConfig.
   *
   * @param string $systemPrompt
   *   The system prompt sent to the LLM at the start of every API call.
   *   Should describe the assistant's role, capabilities, and any
   *   content-specific context (e.g. the content schema for drafting).
   * @param array $conversationHistory
   *   Array of message arrays with at least 'role' and 'content' keys,
   *   representing the turns that occurred before the current request.
   *   Tool call/result messages appended during the loop are NOT persisted
   *   back here; the caller receives the full updated array in LlmLoopResult.
   * @param \Drupal\ai\OperationType\Chat\Tools\ToolsInput $tools
   *   The tool definitions exposed to the LLM. Each tool definition
   *   describes a function the LLM can call by name, including its
   *   parameter schema and description.
   * @param string $providerId
   *   The AI provider plugin ID as registered in the Drupal AI module
   *   (e.g. 'mistral'). Used to instantiate the correct provider plugin.
   * @param string $modelId
   *   The model identifier string understood by the chosen provider
   *   (e.g. 'mistral-large-latest'). Passed to setConfiguration() and
   *   chat() on the provider instance.
   * @param string $messageId
   *   The initial SSE message envelope ID. Used by AgUiState to correlate
   *   startMessage/finishMessage events. A new UUID is generated by the loop
   *   for each subsequent tool-call iteration so message IDs remain unique
   *   within a single streaming response.
   * @param \Closure $toolExecutor
   *   Callback invoked when the LLM returns tool calls. Signature:
   *   fn(array $toolCallsForExec) => array $toolResultMessages.
   *   The $toolCallsForExec array maps tool call ID (string) to an array
   *   with 'name' (string) and 'arguments' (array) keys. The returned
   *   array must be a list of message arrays suitable for appending to
   *   the conversation history (each with 'role' => 'tool',
   *   'tool_call_id', and 'content' keys).
   *   The loop emits startToolCall() before calling this closure and
   *   finishToolCall() after it returns.
   * @param int $maxIterations
   *   Maximum number of tool-call loop iterations before the loop exits
   *   even if the LLM has not produced a final text response. This guards
   *   against runaway tool-call chains caused by misbehaving LLM output.
   *   Default is 10, which is sufficient for all current plugin use cases.
   * @param \Closure|null $onToolCallArgumentDelta
   *   Optional callback invoked during the streaming iteration when
   *   partial tool call arguments are detected. Signature:
   *   fn(array $partialToolCalls): void. Each element of the array
   *   has keys 'id' (string), 'name' (string), and
   *   'arguments_json' (string). Called on every chunk that carries
   *   tool call data, allowing plugins to stream field values
   *   incrementally before the tool call completes. NULL disables
   *   incremental streaming (the default).
   */
  public function __construct(
    public readonly string $systemPrompt,
    public readonly array $conversationHistory,
    public readonly ToolsInput $tools,
    public readonly string $providerId,
    public readonly string $modelId,
    public readonly string $messageId,
    public readonly \Closure $toolExecutor,
    public readonly int $maxIterations = 10,
    public readonly ?\Closure $onToolCallArgumentDelta = NULL,
  ) {}

}
