<?php

declare(strict_types=1);

namespace Drupal\oe_ai_assistant\Service;

use JsonSchema\Validator;

/**
 * Validates request bodies against OpenAPI schemas.
 *
 * Reads the consolidated schemas.json from the dist/ directory (produced
 * by the React app build step) and uses justinrainbow/json-schema for
 * validation. This ensures that every incoming plugin request body
 * conforms to the OpenAPI contract before any business logic runs.
 *
 * The schemas.json file is generated by the frontend build from the
 * OpenAPI spec (app/api/openapi.yaml). It is a flat object whose keys
 * are schema names (e.g. 'EchoRequest', 'DraftingChatRequest') and
 * whose values are JSON Schema objects. This mirrors the components/schemas
 * section of the OpenAPI spec.
 *
 * Schema definitions are loaded from disk once per request and cached in
 * memory. If the file does not exist (e.g. the frontend has not been built),
 * all validation calls return an "Unknown schema" error rather than throwing
 * an exception, allowing callers to surface a clean HTTP 400 response.
 */
class RequestValidator {

  /**
   * Cached schema definitions keyed by schema name.
   *
   * NULL means the schemas have not been loaded yet (not that loading
   * failed). After the first loadSchemas() call this will be an array
   * (possibly empty if the file was absent or unreadable).
   *
   * @var array<string, object>|null
   */
  private ?array $schemas = NULL;

  /**
   * Validates a raw JSON string against a named schema.
   *
   * Decodes the JSON as objects (not associative arrays) because the
   * justinrainbow/json-schema validator distinguishes between JSON objects
   * (stdClass) and JSON arrays (array). Decoding as stdClass ensures that
   * empty JSON objects ({}) are treated as objects rather than empty PHP
   * arrays ([]), which would fail object-type assertions in the schema.
   *
   * @param string $rawJson
   *   The raw JSON string from the request body (e.g. from
   *   Request::getContent()).
   * @param string $schemaName
   *   The schema name to validate against, matching a key in schemas.json
   *   (e.g. 'EchoRequest', 'DraftingChatRequest').
   *
   * @return string[]
   *   Array of human-readable validation error messages. An empty array
   *   means the request body is valid. Each message is prefixed with the
   *   JSON property path when available (e.g. "threadId: This value is
   *   required.").
   */
  public function validateRaw(string $rawJson, string $schemaName): array {
    $schemas = $this->loadSchemas();

    if (!isset($schemas[$schemaName])) {
      // The schema name was not found; this is a programming error (wrong
      // schema name passed by the caller) rather than a client error.
      return [sprintf("Unknown schema '%s'.", $schemaName)];
    }

    $schema = $schemas[$schemaName];

    // Decode as objects (not associative arrays) so the validator sees {}
    // as stdClass, not an empty PHP array. json_decode() returns NULL on
    // parse failure; JSON_ERROR_NONE means the input was literally 'null'
    // which may still be a valid schema value depending on the schema.
    $data = json_decode($rawJson);
    if ($data === NULL && json_last_error() !== JSON_ERROR_NONE) {
      return ['Invalid JSON in request body.'];
    }

    $validator = new Validator();
    $validator->validate($data, $schema);

    if ($validator->isValid()) {
      return [];
    }

    // Collect and format all validation errors. The property key is the
    // dot-notation JSON path to the failing field (e.g. 'fields.title').
    // An empty property string means the error is at the root level.
    $errors = [];
    foreach ($validator->getErrors() as $error) {
      $path = $error['property'] ? $error['property'] . ': ' : '';
      $errors[] = $path . $error['message'];
    }

    return $errors;
  }

  /**
   * Loads and caches schema definitions from dist/schemas.json.
   *
   * Resolves the path to schemas.json relative to the module root (two
   * directory levels above this file). Decodes the JSON as objects
   * (stdClass) because the json-schema validator needs the schema
   * definitions to be object trees, not associative arrays.
   *
   * Returns an empty array (and caches it) when the file does not exist
   * or contains invalid JSON, so subsequent calls within the same request
   * do not retry disk reads unnecessarily.
   *
   * @return array<string, object>
   *   Map of schema name (string) to schema definition (stdClass). The
   *   stdClass objects are the exact representation expected by the
   *   justinrainbow/json-schema Validator::validate() method.
   */
  private function loadSchemas(): array {
    // Return the in-memory cache on subsequent calls.
    if ($this->schemas !== NULL) {
      return $this->schemas;
    }

    // Resolve the module root from this file's location:
    // src/Service/RequestValidator.php -> module root is two levels up.
    $moduleRoot = dirname(__DIR__, 2);
    $schemaFile = $moduleRoot . '/dist/schemas.json';

    if (!file_exists($schemaFile)) {
      // Cache the empty array so repeated calls do not stat the filesystem.
      $this->schemas = [];
      return $this->schemas;
    }

    // Decode as objects (FALSE/omit second arg): the json-schema library
    // expects stdClass trees, not associative PHP arrays.
    $raw = json_decode(file_get_contents($schemaFile), FALSE);

    if (!is_object($raw)) {
      // The file exists but contains invalid JSON or is not a JSON object.
      $this->schemas = [];
      return $this->schemas;
    }

    // Build a flat map of schema name to schema definition object.
    // This avoids repeated property access on the root stdClass object
    // and makes the isset() lookup in validateRaw() explicit and fast.
    $this->schemas = [];
    foreach ($raw as $name => $definition) {
      $this->schemas[$name] = $definition;
    }

    return $this->schemas;
  }

}
