#!/bin/bash

## Description: Full rebuild: composer install, symlink, and install the site
## Usage: rebuild
## Example: ddev rebuild

set -e

echo "Installing dependencies..."
ddev poser

echo "Symlinking module into Drupal..."
export PROJECT_FILES=$(ls -A)
ddev symlink-project

ddev build-app
ddev install
