<?php

declare(strict_types=1);

namespace Drupal\oe_ai_assistant\Tool;

use Drupal\Component\Serialization\Json;
use Psr\Log\LoggerInterface;

/**
 * Tool callable for the draft_content LLM function.
 *
 * Handles the draft_content tool call from the LLM: validates and
 * filters field values against the known field index, and returns
 * a structured result for the LLM's conversation history.
 *
 * This tool is pure -- it does not emit SSE events. Side effects
 * like STATE_SNAPSHOT emission are handled by event listeners on
 * the ToolCallSucceeded event, registered by DraftingPlugin.
 *
 * This class is instantiated per-request by DraftingPlugin with
 * the current field index.
 */
class DraftContentTool {

  /**
   * Constructs a DraftContentTool.
   *
   * @param array<string, mixed> $fieldIndex
   *   Map of known field machine names to metadata. Only fields
   *   present in this index are included in the result.
   * @param \Psr\Log\LoggerInterface $logger
   *   Logger for reporting unknown fields from the LLM.
   */
  public function __construct(
    private readonly array $fieldIndex,
    private readonly LoggerInterface $logger,
  ) {}

  /**
   * Executes the draft_content tool call.
   *
   * @param array<string, mixed> $fields
   *   Field values keyed by machine name, as generated by the LLM.
   * @param string[] $changed_fields
   *   List of field machine names that were modified in this call.
   *
   * @return string
   *   JSON-encoded result for the LLM conversation history.
   */
  public function __invoke(
    array $fields,
    array $changed_fields = [],
  ): string {
    // Filter fields against the schema. Only fields present in
    // the field index are included. Log unknown fields so we can
    // tune the prompt or schema if needed.
    if (!empty($this->fieldIndex)) {
      $unknownFields = array_diff_key($fields, $this->fieldIndex);
      if (!empty($unknownFields)) {
        $this->logger->notice(
          'LLM generated unknown fields: @fields',
          ['@fields' => implode(', ', array_keys($unknownFields))],
        );
      }
      $fields = array_intersect_key($fields, $this->fieldIndex);
    }

    return Json::encode([
      'success' => TRUE,
      'fields' => $fields,
      'changedFields' => $changed_fields,
      'message' => 'Draft content generated with '
        . count($fields) . ' fields.',
    ]);
  }

}
