/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/state/{nodeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Load persisted application state for a content node. */
        get: operations["getState"];
        /** Save application state for a content node. */
        put: operations["saveState"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/content-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List available content types.
         * @description Returns the content types the current user can work with. Each entry includes the type's field schema so plugins know which fields are available.
         */
        get: operations["listContentTypes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/content-types/{contentTypeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single content type definition. */
        get: operations["getContentType"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plugins/{pluginId}/get-messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Load the persisted conversation transcript for a session */
        post: operations["postGetMessages"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plugins/drafting/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send a drafting message and receive AG-UI SSE stream */
        post: operations["postDraftingChat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plugins/drafting/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset the drafting conversation thread */
        post: operations["postDraftingReset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plugins/drafting/save": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Save a session draft version as an unpublished node */
        post: operations["postDraftingSave"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plugins/drafting/set-tone": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set selected drafting tone */
        post: operations["postDraftingSetTone"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plugins/drafting/set-template": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set the selected drafting template on the session */
        post: operations["postDraftingSetTemplate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plugins/drafting/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Render a themed HTML preview of a stored draft version, without saving */
        get: operations["getDraftingPreview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plugins/echo/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Echo a message back as an SSE stream (dev-only).
         * @description Accepts a message and streams it back word-by-word as Server-Sent Events. Used to test SSE consumption in the frontend. Not available in production.
         */
        post: operations["postEchoStream"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plugins/notes/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** List all notes (dev-only). */
        post: operations["notesList"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plugins/notes/get": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Get a single note by ID (dev-only). */
        post: operations["notesGet"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plugins/notes/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a new note (dev-only). */
        post: operations["notesCreate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plugins/notes/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Update an existing note (dev-only). */
        post: operations["notesUpdate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plugins/notes/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Delete a note (dev-only). */
        post: operations["notesDelete"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Standard error envelope returned by all error responses. */
        ApiError: {
            /** @description Machine-readable error code (e.g. "not_found"). */
            code: string;
            /** @description Human-readable explanation. */
            message: string;
        };
        /** @description Opaque JSON blob representing the full persisted application state. The backend stores it as-is and returns it verbatim. The shape is owned by the frontend Zustand store. */
        AppStateBlob: {
            [key: string]: unknown;
        };
        /** @description Describes a single field within a content type. */
        ContentTypeField: {
            /** @description Machine name (used as the key in content fields). */
            name: string;
            /** @description Human-readable label. */
            label: string;
            /**
             * @description Field widget type.
             * @enum {string}
             */
            type: "text" | "textarea" | "html" | "select" | "boolean" | "number";
            /**
             * @description Whether the field is required.
             * @default false
             */
            required: boolean;
            /** @description Allowed values for select fields. */
            options?: {
                value: string;
                label: string;
            }[];
        };
        /** @description A content type definition. Tells the app which fields are available for a given type of content. */
        ContentType: {
            /** @description Machine name (e.g. "article", "news_story"). */
            id: string;
            /** @description Human-readable name. */
            name: string;
            /** @description Short explanation of the content type. */
            description?: string;
            /** @description Ordered list of fields the editor can fill. */
            fields: components["schemas"]["ContentTypeField"][];
        };
        /** @description Load the persisted conversation transcript for an editorial session. Available on every plugin endpoint under /plugins/{pluginId}/get-messages. */
        GetMessagesRequest: {
            /** @description The editorial session whose transcript to load. */
            sessionId: string;
        };
        GetMessagesResponse: {
            /** @description The user-visible transcript, oldest first. */
            messages: {
                /** @description The message role ("user", "assistant" or "event"). */
                role: string;
                /** @description The message text (user and assistant items). */
                content?: string;
                /** @description Display name of the author (user items). Together with userId it attributes turns in shared sessions. */
                userName?: string;
                /** @description Stable CMS user id of the author (user items). Clients key participants by this id so two users sharing a display name stay distinct. */
                userId?: string;
                /** @description The event type, e.g. "session_start", "tone", "template" (event items). */
                type?: string;
                /** @description The human-readable event summary (event items). */
                summary?: string;
                /** @description RFC 3339 timestamp of the event (event items). */
                at?: string;
                /** @description The draft version a "save" event persisted (event items). */
                version?: number;
            }[];
        };
        DraftingChatRequest: {
            /** @description The user's drafting prompt or instruction. */
            message: string;
            /** @description The editorial session that hosts the conversation. The backend derives the target content type and access from the session and persists every turn against it. */
            sessionId: string;
        };
        DraftingResetRequest: {
            /** @description The editorial session whose conversation to reset. */
            sessionId: string;
        };
        DraftingResetResponse: {
            /** @description Confirmation status (e.g. "ok"). */
            status: string;
        };
        /** @description Save one of the session's drafts as an unpublished revision. The backend resolves the target content type and the drafted field values from the session and its draft history, so the client only names the version being saved; a client can never save field data the session did not produce. */
        DraftingSaveRequest: {
            /** @description The editorial session that owns the draft. */
            sessionId: string;
            /** @description The draft version to save, matching the version of a draft_content result in the session transcript (the version shown in the artifact pane and the version rail). */
            version: number;
        };
        DraftingSaveResponse: {
            /** @description The ID of the created node. */
            nodeId: string;
            /** @description URL to preview the created draft node. */
            previewUrl: string;
        };
        DraftingSetToneRequest: {
            /** @description The editorial session on which the selected tone is saved. */
            sessionId: string;
            /** @description Selected tone taxonomy term ID. */
            toneId: string;
        };
        DraftingSetToneResponse: {
            /** @enum {string} */
            status: "ok";
        };
        DraftingSetTemplateRequest: {
            /** @description The editorial session on which the selected template is saved. */
            sessionId: string;
            /** @description The ai_drafting_template id to select, from pluginConfig.drafting.templates.options. The template field is mandatory, so an empty value is rejected. */
            template: string;
        };
        DraftingSetTemplateResponse: {
            /** @description Confirmation status (e.g. "ok"). */
            status: string;
        };
        /** @description Request body for the echo stream endpoint. */
        EchoRequest: {
            /** @description Text to echo back word-by-word. */
            message: string;
        };
        /** @description A single SSE data frame from the echo stream. */
        EchoStreamEvent: {
            /** @description The word being streamed back. */
            word: string;
            /** @description Zero-based index of this word in the original message. */
            index: number;
            /** @description True when this is the last event in the stream. */
            done: boolean;
        };
        /** @description A note stored in the mock backend. */
        Note: {
            id: string;
            title: string;
            content: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        /** @description Request body for the list action (currently empty). */
        NotesListRequest: Record<string, never>;
        /** @description Request body for the get action. */
        NotesGetRequest: {
            /** @description ID of the note to retrieve. */
            noteId: string;
        };
        /** @description Request body for the create action. */
        NotesCreateRequest: {
            title: string;
            content: string;
        };
        /** @description Request body for the update action. */
        NotesUpdateRequest: {
            /** @description ID of the note to update. */
            noteId: string;
            title: string;
            content: string;
        };
        /** @description Request body for the delete action. */
        NotesDeleteRequest: {
            /** @description ID of the note to delete. */
            noteId: string;
        };
    };
    responses: {
        /** @description Authentication required or insufficient permissions. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
    };
    parameters: {
        /** @description CMS content node identifier. */
        NodeId: string;
        /** @description Machine name of a content type. */
        ContentTypeId: string;
        /** @description Machine name of the plugin dispatching the action. */
        PluginId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getState: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description CMS content node identifier. */
                nodeId: components["parameters"]["NodeId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description State blob for this node. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppStateBlob"];
                };
            };
            403: components["responses"]["Forbidden"];
            /** @description No persisted state found for this node. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    saveState: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description CMS content node identifier. */
                nodeId: components["parameters"]["NodeId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AppStateBlob"];
            };
        };
        responses: {
            /** @description State saved successfully. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Forbidden"];
        };
    };
    listContentTypes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of content type definitions. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        contentTypes: components["schemas"]["ContentType"][];
                    };
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    getContentType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Machine name of a content type. */
                contentTypeId: components["parameters"]["ContentTypeId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Content type definition. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContentType"];
                };
            };
            403: components["responses"]["Forbidden"];
            /** @description Content type not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    postGetMessages: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Machine name of the plugin dispatching the action. */
                pluginId: components["parameters"]["PluginId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GetMessagesRequest"];
            };
        };
        responses: {
            /** @description The user-visible transcript */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetMessagesResponse"];
                };
            };
        };
    };
    postDraftingChat: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DraftingChatRequest"];
            };
        };
        responses: {
            /** @description SSE stream of AG-UI protocol events */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": unknown;
                };
            };
        };
    };
    postDraftingReset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DraftingResetRequest"];
            };
        };
        responses: {
            /** @description Reset confirmation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftingResetResponse"];
                };
            };
        };
    };
    postDraftingSave: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DraftingSaveRequest"];
            };
        };
        responses: {
            /** @description Created node details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftingSaveResponse"];
                };
            };
        };
    };
    postDraftingSetTone: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DraftingSetToneRequest"];
            };
        };
        responses: {
            /** @description Selected tone accepted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftingSetToneResponse"];
                };
            };
            /** @description Validation error. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    postDraftingSetTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DraftingSetTemplateRequest"];
            };
        };
        responses: {
            /** @description Set-template confirmation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftingSetTemplateResponse"];
                };
            };
            /** @description Validation error. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    getDraftingPreview: {
        parameters: {
            query: {
                /** @description The editorial session hosting the draft to preview. */
                sessionId: string;
                /** @description The draft version to render, as returned by get_draft_history / the draft_content result (e.g. 1 for "Draft 1"). */
                version: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A complete, standalone HTML document rendering the draft as the live site would show it. Not JSON: the action is a GET so an iframe can load it directly through its src attribute. The rendered document contains LLM-authored content, so consuming iframes should sandbox it (no script execution) rather than grant full same-origin trust. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
            /** @description Validation error, unresolvable template, or invalid payload. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Missing create permission for the bundle. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description The requested draft version was not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Rendering failed. See the system log for details. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    postEchoStream: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EchoRequest"];
            };
        };
        responses: {
            /** @description SSE stream echoing the message word-by-word. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            /** @description Missing or empty message. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    notesList: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NotesListRequest"];
            };
        };
        responses: {
            /** @description Array of notes, newest first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Note"][];
                };
            };
        };
    };
    notesGet: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NotesGetRequest"];
            };
        };
        responses: {
            /** @description The note. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Note"];
                };
            };
            /** @description Note not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    notesCreate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NotesCreateRequest"];
            };
        };
        responses: {
            /** @description Note created. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Note"];
                };
            };
            /** @description Validation error. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    notesUpdate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NotesUpdateRequest"];
            };
        };
        responses: {
            /** @description Note updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Note"];
                };
            };
            /** @description Note not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    notesDelete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NotesDeleteRequest"];
            };
        };
        responses: {
            /** @description Note deleted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Note not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
}
