/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/state/{nodeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Load persisted application state for a content node. */
        get: operations["getState"];
        /** Save application state for a content node. */
        put: operations["saveState"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/content-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List available content types.
         * @description Returns the content types the current user can work with. Each entry includes the type's field schema so plugins know which fields are available.
         */
        get: operations["listContentTypes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/content-types/{contentTypeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single content type definition. */
        get: operations["getContentType"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plugins/drafting/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send a drafting message and receive AG-UI SSE stream */
        post: operations["postDraftingChat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plugins/drafting/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset the drafting conversation thread */
        post: operations["postDraftingReset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plugins/drafting/save": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Save an approved draft as an unpublished node */
        post: operations["postDraftingSave"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plugins/echo/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Echo a message back as an SSE stream (dev-only).
         * @description Accepts a message and streams it back word-by-word as Server-Sent Events. Used to test SSE consumption in the frontend. Not available in production.
         */
        post: operations["postEchoStream"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plugins/notes/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** List all notes (dev-only). */
        post: operations["notesList"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plugins/notes/get": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Get a single note by ID (dev-only). */
        post: operations["notesGet"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plugins/notes/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a new note (dev-only). */
        post: operations["notesCreate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plugins/notes/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Update an existing note (dev-only). */
        post: operations["notesUpdate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plugins/notes/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Delete a note (dev-only). */
        post: operations["notesDelete"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Standard error envelope returned by all error responses. */
        ApiError: {
            /** @description Machine-readable error code (e.g. "not_found"). */
            code: string;
            /** @description Human-readable explanation. */
            message: string;
        };
        /** @description Opaque JSON blob representing the full persisted application state. The backend stores it as-is and returns it verbatim. The shape is owned by the frontend Zustand store. */
        AppStateBlob: {
            [key: string]: unknown;
        };
        /** @description Describes a single field within a content type. */
        ContentTypeField: {
            /** @description Machine name (used as the key in content fields). */
            name: string;
            /** @description Human-readable label. */
            label: string;
            /**
             * @description Field widget type.
             * @enum {string}
             */
            type: "text" | "textarea" | "html" | "select" | "boolean" | "number";
            /**
             * @description Whether the field is required.
             * @default false
             */
            required: boolean;
            /** @description Allowed values for select fields. */
            options?: {
                value: string;
                label: string;
            }[];
        };
        /** @description A content type definition. Tells the app which fields are available for a given type of content. */
        ContentType: {
            /** @description Machine name (e.g. "article", "news_story"). */
            id: string;
            /** @description Human-readable name. */
            name: string;
            /** @description Short explanation of the content type. */
            description?: string;
            /** @description Ordered list of fields the editor can fill. */
            fields: components["schemas"]["ContentTypeField"][];
        };
        DraftingChatRequest: {
            /** @description The user's drafting prompt or instruction. */
            message: string;
            /** @description Optional thread ID for conversation continuity. Omit to start a new conversation. */
            threadId?: string;
            /** @description Optional AI editorial session ID. When provided, the backend stores conversation continuity in the session-scoped drafting plugin state. */
            sessionId?: string;
            /** @description The entity type ID (e.g. "node"). */
            entityTypeId: string;
            /** @description The content type machine name (e.g. "oe_news"). */
            bundle: string;
            /** @description The full form schema for the target content type, as returned by GET /content-schema/{entityTypeId}/{bundle}?mode=form. */
            schema: Record<string, never>;
        };
        DraftingResetRequest: {
            /** @description The thread ID of the conversation to reset. */
            threadId: string;
        };
        DraftingResetResponse: {
            /** @description The new thread ID for the reset conversation. */
            threadId: string;
        };
        DraftingSaveRequest: {
            /** @description The entity type ID (e.g. "node"). */
            entityTypeId: string;
            /** @description The content type machine name (e.g. "oe_news"). */
            bundle: string;
            /** @description The drafted field values, keyed by field machine name. Shape matches the content type form schema. */
            fields: Record<string, never>;
        };
        DraftingSaveResponse: {
            /** @description The ID of the created node. */
            nodeId: string;
            /** @description URL to preview the created draft node. */
            previewUrl: string;
        };
        /** @description Request body for the echo stream endpoint. */
        EchoRequest: {
            /** @description Text to echo back word-by-word. */
            message: string;
        };
        /** @description A single SSE data frame from the echo stream. */
        EchoStreamEvent: {
            /** @description The word being streamed back. */
            word: string;
            /** @description Zero-based index of this word in the original message. */
            index: number;
            /** @description True when this is the last event in the stream. */
            done: boolean;
        };
        /** @description A note stored in the mock backend. */
        Note: {
            id: string;
            title: string;
            content: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        /** @description Request body for the list action (currently empty). */
        NotesListRequest: Record<string, never>;
        /** @description Request body for the get action. */
        NotesGetRequest: {
            /** @description ID of the note to retrieve. */
            noteId: string;
        };
        /** @description Request body for the create action. */
        NotesCreateRequest: {
            title: string;
            content: string;
        };
        /** @description Request body for the update action. */
        NotesUpdateRequest: {
            /** @description ID of the note to update. */
            noteId: string;
            title: string;
            content: string;
        };
        /** @description Request body for the delete action. */
        NotesDeleteRequest: {
            /** @description ID of the note to delete. */
            noteId: string;
        };
    };
    responses: {
        /** @description Authentication required or insufficient permissions. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
    };
    parameters: {
        /** @description CMS content node identifier. */
        NodeId: string;
        /** @description Machine name of a content type. */
        ContentTypeId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getState: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description CMS content node identifier. */
                nodeId: components["parameters"]["NodeId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description State blob for this node. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppStateBlob"];
                };
            };
            403: components["responses"]["Forbidden"];
            /** @description No persisted state found for this node. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    saveState: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description CMS content node identifier. */
                nodeId: components["parameters"]["NodeId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AppStateBlob"];
            };
        };
        responses: {
            /** @description State saved successfully. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Forbidden"];
        };
    };
    listContentTypes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of content type definitions. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        contentTypes: components["schemas"]["ContentType"][];
                    };
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    getContentType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Machine name of a content type. */
                contentTypeId: components["parameters"]["ContentTypeId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Content type definition. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContentType"];
                };
            };
            403: components["responses"]["Forbidden"];
            /** @description Content type not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    postDraftingChat: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DraftingChatRequest"];
            };
        };
        responses: {
            /** @description SSE stream of AG-UI protocol events */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": unknown;
                };
            };
        };
    };
    postDraftingReset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DraftingResetRequest"];
            };
        };
        responses: {
            /** @description New thread ID */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftingResetResponse"];
                };
            };
        };
    };
    postDraftingSave: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DraftingSaveRequest"];
            };
        };
        responses: {
            /** @description Created node details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftingSaveResponse"];
                };
            };
        };
    };
    postEchoStream: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EchoRequest"];
            };
        };
        responses: {
            /** @description SSE stream echoing the message word-by-word. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            /** @description Missing or empty message. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    notesList: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NotesListRequest"];
            };
        };
        responses: {
            /** @description Array of notes, newest first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Note"][];
                };
            };
        };
    };
    notesGet: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NotesGetRequest"];
            };
        };
        responses: {
            /** @description The note. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Note"];
                };
            };
            /** @description Note not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    notesCreate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NotesCreateRequest"];
            };
        };
        responses: {
            /** @description Note created. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Note"];
                };
            };
            /** @description Validation error. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    notesUpdate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NotesUpdateRequest"];
            };
        };
        responses: {
            /** @description Note updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Note"];
                };
            };
            /** @description Note not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    notesDelete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NotesDeleteRequest"];
            };
        };
        responses: {
            /** @description Note deleted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Note not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
}
