services:
  playwright:
    image: mcr.microsoft.com/playwright:v1.59.1-noble
    container_name: ddev-${DDEV_SITENAME}-playwright
    working_dir: /app
    volumes:
      - "../:/app:cached"
    entrypoint: ["tail", "-f", "/dev/null"]
    environment:
      - BASE_URL=http://web
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    depends_on:
      - web
